send a LastHttpContent marker after a ChunkedStream
In case a resource was not a FileSystemResource, the HTTP response was
not correctly terminated, which - when using HTTP/1.1 keepAlive -
resulted in the following exception to be thrown for the next request:

```
could not write header io.netty.handler.codec.EncoderException:
  java.lang.IllegalStateException: unexpected message type: DefaultHttpResponse
  ...
Caused by:
  java.lang.IllegalStateException: unexpected message type: DefaultHttpResponse
```